apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfm-service
  namespace: default
  labels:
      app: pfm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfm-service
  template:
    metadata:
      labels:
        app: pfm-service
    spec:
      containers:
      - name: pfm-service
        image: 212760202707.dkr.ecr.us-east-1.amazonaws.com/pfm-service:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /pfm-service/monitoring/health-check/
            port: 8000
        readinessProbe:
          httpGet:
            path: /pfm-service/monitoring/health-check/
            port: 8000
        envFrom:
        - secretRef:
            name: pfm-service-secret
        - secretRef:
            name: shared-secret
        command:  ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]
        ports:
          - name: tcp
            containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      - name: core-service
        image: 212760202707.dkr.ecr.us-east-1.amazonaws.com/core-service:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /core-service/monitoring/health-check/
            port: 8001
        readinessProbe:
          httpGet:
            path: /core-service/monitoring/health-check/
            port: 8001
        envFrom:
        - secretRef:
            name: core-service-secret
        - secretRef:
            name: shared-secret
        command:  ["python", "src/manage.py", "runserver", "0.0.0.0:8001"]
        ports:
          - name: tcp
            containerPort: 8001
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      - name: config-service
        image: 212760202707.dkr.ecr.us-east-1.amazonaws.com/config-service:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /config-service/monitoring/health-check/
            port: 8002
        readinessProbe:
          httpGet:
            path: /config-service/monitoring/health-check/
            port: 8002
        envFrom:
        - secretRef:
            name: config-service-secret
        - secretRef:
            name: shared-secret
        command:  ["python", "src/manage.py", "runserver", "0.0.0.0:8002"]
        ports:
          - name: tcp
            containerPort: 8002
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      - name: catalog-service
        image: 212760202707.dkr.ecr.us-east-1.amazonaws.com/catalog-service:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /catalog-service/monitoring/health-check/
            port: 8003
        readinessProbe:
          httpGet:
            path: /catalog-service/monitoring/health-check/
            port: 8003
        envFrom:
        - secretRef:
            name: catalog-service-secret
        - secretRef:
            name: shared-secret
        command:  ["python", "src/manage.py", "runserver", "0.0.0.0:8003"]
        ports:
          - name: tcp
            containerPort: 8003
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: pfm-service
  namespace: default
  labels:
    app: pfm-service
spec:
  type: ClusterIP
  selector:
    app: pfm-service
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: default
  labels:
    app: core-service
spec:
  type: ClusterIP
  selector:
    app: core-service
  ports:
    - port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: default
  labels:
    app: config-service
spec:
  type: ClusterIP
  selector:
    app: config-service
  ports:
    - port: 8002
      targetPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: default
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog-service
  ports:
    - port: 8003
      targetPort: 8003
