apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: default
  labels:
      app: core-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
      - name: core-service
        image: 212760202707.dkr.ecr.us-east-1.amazonaws.com/core-service:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /core-service/monitoring/health-check/
            port: 8000
        readinessProbe:
          httpGet:
            path: /core-service/monitoring/health-check/
            port: 8000
        envFrom:
        - secretRef:
            name: core-service-secret
        - secretRef:
            name: shared-secret
        command:  ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]
        ports:
          - name: tcp
            containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: default
  labels:
    app: core-service
spec:
  type: ClusterIP
  selector:
    app: core-service
  ports:
    - port: 8000
      targetPort: 8000
